CREATE TABLE HOME_ADDRESS(
ADRESS_ID INTEGER PRIMARY KEY,
ADRESS VARCHAR(50) not null,
PHONE INTEGER not null
);
insert into HOME_ADDRESS (ADRESS_ID,ADRESS,PHONE) values (5,'1913 Hanoi Way',2541545);
INSERT INTO HOME_ADDRESS (ADRESS_ID, ADRESS, PHONE) VALUES (7,  '692 Joliet Street'  ,  44847719);
INSERT INTO HOME_ADDRESS (ADRESS_ID, ADRESS, PHONE) VALUES (8,  '1566 Inegl Manor'  ,  70581400);
INSERT INTO HOME_ADDRESS (ADRESS_ID, ADRESS, PHONE) VALUES (10,  '1795 Santiago '  ,  86045262);
INSERT INTO HOME_ADDRESS (ADRESS_ID, ADRESS, PHONE) VALUES (11,  '900 Santiago '  ,  16571220);

SELECT * FROM HOME_ADDRESS;

CREATE TABLE CUSTOMERS(
  CUSTOMER_ID INTEGER PRIMARY KEY ,
  FIRST_NAME VARCHAR(20) NOT NULL ,
  LAST_NAME VARCHAR(20) NOT NULL ,
  ADDRESS_ID INTEGER REFERENCES HOME_ADDRESS(ADRESS_ID)-- İKİ tablo arasında ilişki kurdu
);
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES (1, 'Mary' ,  'Smith',  5);
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES (2,  'Patricia' ,  'Johnson' ,  NULl);
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES (3,  'Linda' ,  'Williams' ,  7);
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES (4, 'Barbara' ,  'Jones' , 8);
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, ADDRESS_ID) VALUES (5,  'Elizabeth' ,  'Brown' ,  NULL);

COMMIT WORK ;
select *FROM CUSTOMERS;